import "./globals.css";
import { Provider } from "../components/ui/provider";

export const metadata = {
  title: "صفحه اصلی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Provider>

        {children}
        </Provider>
      </body>
    </html>
  );
}
